{
 "title": "Celery tasks",
 "tags": [ "celery" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(celery_tasks,namespace)"
   },
   {
    "name": "microservice",
    "label": "Service",
    "query": "label_values(celery_tasks{namespace=\"$namespace\"},microservice)"
   }
  ]
 },
 "panels": [
  {
   "title": "Pending tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(celery_tasks{state=\"PENDING\",namespace=\"$namespace\",microservice=~\"$microservice\"})"
    }
   ]
  },
  {
   "title": "Started tasks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(celery_tasks{state=\"STARTED\",namespace=\"$namespace\",microservice=~\"$microservice\"})"
    }
   ]
  },
  {
   "title": "Efficiency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - sum(celery_tasks{state=\"FAILURE\",namespace=\"$namespace\",microservice=~\"$microservice\"}) / sum(celery_tasks{state=\"SUCCESS\",namespace=\"$namespace\",microservice=~\"$microservice\"})"
    }
   ]
  },
  {
   "title": "Most failured task",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 15, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "topk(1,task:celery_failure_tasks{namespace=\"$namespace\",microservice=~\"$microservice\"}) > 0",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Tasks by service name stats",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(celery_workers{namespace=\"$namespace\",microservice=~\"$microservice\"}) without (instance,pod,endpoint)"
    },
    {
     "expr": "sum(celery_tasks{namespace=\"$namespace\",microservice=~\"$microservice\",state=\"RECEIVED\"}) without (instance,pod,endpoint,state)"
    },
    {
     "expr": "sum(celery_tasks{namespace=\"$namespace\",microservice=~\"$microservice\",state=\"PENDING\"}) without (instance,pod,endpoint,state)"
    },
    {
     "expr": "sum(celery_tasks{namespace=\"$namespace\",microservice=~\"$microservice\",state=\"STARTED\"}) without (instance,pod,endpoint,state)"
    },
    {
     "expr": "sum(celery_tasks{namespace=\"$namespace\",microservice=~\"$microservice\",state=\"SUCCESS\"}) without (instance,pod,endpoint,state)"
    },
    {
     "expr": "sum(celery_tasks{namespace=\"$namespace\",microservice=~\"$microservice\",state=\"FAILURE\"}) without (instance,pod,endpoint,state)"
    },
    {
     "expr": "sum(celery_tasks{namespace=\"$namespace\",microservice=~\"$microservice\",state=\"REVOKED\"}) without (instance,pod,endpoint,state)"
    },
    {
     "expr": "sum(celery_tasks{namespace=\"$namespace\",microservice=~\"$microservice\",state=\"RETRY\"}) without (instance,pod,endpoint,state)"
    }
   ]
  },
  {
   "title": "Success/failure rate over time (by service)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(service:celery_failure_tasks{namespace=\"$namespace\",microservice=~\"$microservice\"}[5m])",
     "legendFormat": "{{ microservice }} - {{ state }}"
    },
    {
     "expr": "rate(service:celery_success_tasks{namespace=\"$namespace\",microservice=~\"$microservice\"}[5m])",
     "legendFormat": "{{ microservice }} - {{ state }}"
    }
   ]
  },
  {
   "title": "Current tasks overview (by task name)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(celery_tasks_by_name{namespace=\"$namespace\",microservice=~\"$microservice\",state=\"RECEIVED\"}) by (name)"
    },
    {
     "expr": "sum(celery_tasks_by_name{namespace=\"$namespace\",microservice=~\"$microservice\",state=\"PENDING\"}) by (name)"
    },
    {
     "expr": "sum(celery_tasks_by_name{namespace=\"$namespace\",microservice=~\"$microservice\",state=\"STARTED\"}) by (name)"
    },
    {
     "expr": "sum(celery_tasks_by_name{namespace=\"$namespace\",microservice=~\"$microservice\",state=\"SUCCESS\"}) by (name)"
    },
    {
     "expr": "sum(celery_tasks_by_name{namespace=\"$namespace\",microservice=~\"$microservice\",state=\"FAILURE\"}) by (name)"
    },
    {
     "expr": "sum(celery_tasks_by_name{namespace=\"$namespace\",microservice=~\"$microservice\",state=\"REVOKED\"}) by (name)"
    },
    {
     "expr": "sum(celery_tasks_by_name{namespace=\"$namespace\",microservice=~\"$microservice\",state=\"RETRY\"}) by (name)"
    }
   ]
  },
  {
   "title": "Success/failure rate over time (by task name)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(task:celery_success_tasks{namespace=\"$namespace\",microservice=~\"$microservice\"}[5m])",
     "legendFormat": "{{ name }} - {{ state }}"
    },
    {
     "expr": "rate(task:celery_failure_tasks{namespace=\"$namespace\",microservice=~\"$microservice\"}[5m])",
     "legendFormat": "{{ name }} - {{ state }}"
    }
   ]
  }
 ]
}