apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/version: '1.5.1'
  name: celery-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: celery-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: "9540"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: celery-exporter
        app.kubernetes.io/version: '1.5.1'
    spec:
      containers:
        - name: celery-exporter
          image: 4ops/celery-exporter
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: celery-exporter
                optional: true
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 2
            successThreshold: 2
            httpGet:
              scheme: HTTP
              path: /metrics
              port: metrics
          ports:
            - containerPort: 9540
              name: metrics
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1042
            runAsGroup: 1042
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
