apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: celery-exporter
spec:
  groups:
    - name: celery.rules
      rules:
        - expr: sum(celery_tasks{state="FAILURE"}) without (instance,pod,endpoint)
          record: service:celery_failure_tasks
        - expr: sum(celery_tasks{state="SUCCESS"}) without (instance,pod,endpoint)
          record: service:celery_success_tasks
        - expr: sum(celery_tasks_by_name{state="FAILURE"}) without (instance,pod,endpoint)
          record: task:celery_failure_tasks
        - expr: sum(celery_tasks_by_name{state="SUCCESS"}) without (instance,pod,endpoint)
          record: task:celery_success_tasks
        - alert: CeleryErrors
          expr: rate(service:celery_failure_tasks[5m]) > 0.1
          for: 10m
          labels:
            severity: warning
          annotations:
            message: 'Celery task is experiencing {{ printf "%0.0f" $value }} errors / second in namespace `{{ $labels.namespace }}`.'
        - alert: CeleryTaskErrors
          expr: rate(task:celery_failure_tasks[5m]) > 0.1
          for: 10m
          labels:
            severity: warning
          annotations:
            message: 'Task `{{ $labels.name }}` is experiencing {{ printf "%0.0f" $value }} errors / second in namespace `{{ $labels.namespace }}`.'
