apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: celery-exporter
spec:
  endpoints:
    - interval: 30s
      port: metrics
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: celery-exporter
