apiVersion: v1
kind: ConfigMap
metadata:
  name: celery-exporter
data:
  CELERY_EXPORTER_BROKER_URL: redis://redis:6379/0
  CELERY_EXPORTER_LISTEN_ADDRESS: 0.0.0.0:9540
  CELERY_EXPORTER_MAX_TASKS: '10000'
  CELERY_EXPORTER_NAMESPACE: celery
