apiVersion: v1
kind: Service
metadata:
  labels:
    app: celery-prometheus-exporter
    microservice: some-app-name
  name: celery-metrics
spec:
  ports:
    - name: metrics
      port: 8888
      protocol: TCP
      targetPort: 8888
  selector:
    app: celery-prometheus-exporter
    microservice: some-app-name
  sessionAffinity: None
  type: ClusterIP
